In [2]:
import numpy as np

np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.random.randint(50,100,size=(50,5))   #2維


array([[63, 56, 62, 57, 85],
       [74, 69, 99, 68, 84],
       [69, 96, 57, 61, 70],
       [58, 87, 58, 98, 63],
       [74, 95, 52, 75, 98],
       [83, 82, 97, 99, 70],
       [56, 82, 90, 86, 77],
       [86, 92, 73, 52, 77],
       [81, 92, 73, 65, 86],
       [91, 84, 98, 52, 88],
       [91, 69, 72, 82, 70],
       [55, 69, 86, 67, 92],
       [90, 60, 91, 88, 76],
       [57, 98, 71, 95, 98],
       [65, 50, 62, 92, 65],
       [90, 95, 57, 64, 54],
       [70, 55, 73, 96, 96],
       [79, 56, 83, 55, 69],
       [77, 56, 73, 91, 98],
       [87, 66, 85, 94, 75],
       [96, 80, 69, 59, 93],
       [87, 78, 72, 76, 72],
       [85, 76, 53, 77, 76],
       [61, 82, 93, 73, 99],
       [71, 54, 66, 79, 68],
       [94, 72, 57, 59, 50],
       [88, 84, 58, 68, 93],
       [99, 57, 91, 62, 56],
       [53, 80, 87, 72, 93],
       [85, 92, 67, 80, 74],
       [58, 85, 64, 77, 68],
       [66, 96, 51, 80, 81],
       [72, 57, 85, 58, 51],
       [56, 63, 81, 66, 98],
       [95, 69

In [ ]:
np.random.randint(50,100,size=(3,50,5)) #做成三維

array([[[88, 82, 67, 70, 84],
        [79, 73, 86, 98, 82],
        [72, 96, 73, 75, 89],
        [80, 64, 75, 86, 90],
        [74, 93, 50, 83, 84],
        [69, 87, 94, 97, 67],
        [55, 86, 94, 68, 68],
        [52, 65, 86, 79, 60],
        [98, 57, 82, 50, 72],
        [90, 50, 85, 71, 52],
        [88, 53, 56, 50, 78],
        [79, 88, 62, 67, 55],
        [77, 75, 51, 55, 67],
        [86, 57, 97, 71, 94],
        [50, 94, 66, 57, 77],
        [60, 95, 97, 76, 51],
        [86, 50, 53, 93, 85],
        [78, 56, 94, 88, 61],
        [89, 61, 76, 81, 56],
        [74, 68, 97, 92, 87],
        [88, 58, 59, 83, 91],
        [93, 72, 63, 99, 79],
        [76, 70, 92, 65, 92],
        [96, 68, 55, 58, 76],
        [98, 54, 86, 74, 70],
        [56, 66, 74, 74, 84],
        [58, 88, 59, 65, 64],
        [74, 56, 87, 94, 88],
        [58, 95, 88, 62, 59],
        [75, 56, 90, 79, 57],
        [78, 56, 95, 88, 91],
        [84, 79, 91, 69, 73],
        [92, 74, 71, 62, 62],
        [7

In [9]:
#查詢的property->shape,size,dtype,ndim

grade3 = np.random.randint(50,100,size=(3,50,5))
grade3.shape,grade3.size,grade3.ndim,grade3.dtype

((3, 50, 5), 750, 3, dtype('int64'))